# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# A standard Docker workflow, where you are building an image with a Dockerfile in the root of your repository,
# naming the image to be the same name as your repository, pushing to the default docker registry (at docker.io),
# and then updating the image description

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/oc-lettings-tnt78
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/oc-lettings-tnt78
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-pipeline:
    jobs:
      - build-and-push
